import test from 'node:test';
import assert from 'node:assert/strict';
import {validId,validDate,validTime,phoneDigits,reminderKey,israelClock,parseFirebaseServiceAccount,authorizeTenant,publicSettings,overlaps} from '../server/core';
test('tenant IDs reject traversal, arrays, empty input',()=>{for(const v of ['', '../other','a/b',['alex'],'x'.repeat(129),{}])assert.equal(validId(v),false);assert.ok(validId('alex_beauty'));});
test('every supplied tenant selector is authorized',()=>{const a={role:'business_admin',tenantId:'alex'};assert.equal(authorizeTenant(a,[],'other'),'alex');assert.throws(()=>authorizeTenant(a,['alex','other'],'alex'));assert.throws(()=>authorizeTenant(a,['other'],'alex'));assert.throws(()=>authorizeTenant(a,[['alex']],'alex'));});
test('equivalent Israeli phone formats share a reminder key',()=>{const expected=reminderKey('today','0546307114','2026-10-04');for(const p of ['+972546307114','00972546307114','9720546307114','054-6307114'])assert.equal(reminderKey('today',p,'2026-10-04'),expected);assert.equal(phoneDigits('חסימת יומן'),'');assert.notEqual(expected,reminderKey('1day','0546307114','2026-10-04'));});
test('Jerusalem clock handles midnight, UTC host and DST boundaries',()=>{assert.equal(israelClock(new Date('2026-10-03T21:30:00Z')).dateIso,'2026-10-04');assert.equal(israelClock(new Date('2026-10-24T22:30:00Z')).timeStr,'01:30');assert.equal(israelClock(new Date('2026-10-24T23:30:00Z')).timeStr,'01:30');assert.equal(israelClock(new Date('2026-12-31T22:30:00Z')).tomorrowIso,'2027-01-02');});
test('dates/time reject invalid calendar and overflow',()=>{assert.equal(validDate('2026-02-30'),false);assert.equal(validTime('25:00'),false);assert.ok(validDate('2028-02-29'));assert.ok(validTime('08:05'));});
test('credential parser supports JSON, double JSON and base64 without ADC',()=>{const account={project_id:'project',client_email:'test@example.com',private_key:'line1\\nline2'};for(const raw of [JSON.stringify(account),JSON.stringify(JSON.stringify(account)),Buffer.from(JSON.stringify(account)).toString('base64')])assert.equal(parseFirebaseServiceAccount(raw).private_key,'line1\nline2');for(const raw of ['', '{}','not-json','[]'])assert.throws(()=>parseFirebaseServiceAccount(raw));});
test('public SMS payload never includes provider credentials',()=>{assert.deepEqual(publicSettings({telnyxApiKey:'secret',apiKey:'secret',webhookUrl:'secret',password:'secret',morningReminderTime:'08:00'}),{morningReminderTime:'08:00'});});
test('overlap detects intersecting durations but permits touching slots',()=>{const a={status:'confirmed',appointment_date:'2026-10-04',start_time:'10:00',end_time:'11:30'};assert.ok(overlaps(a,{...a,start_time:'10:30',end_time:'12:00'}));assert.equal(overlaps(a,{...a,start_time:'11:30',end_time:'12:00'}),false);assert.equal(overlaps({...a,status:'cancelled'},a),false);});

test('unknown and customer roles cannot receive tenant management permission',()=>{for(const role of ['customer','admin','', 'unexpected'])assert.throws(()=>authorizeTenant({role},['other'],'other'));assert.equal(authorizeTenant({role:'super_admin'},['future_tenant'],'alex'),'future_tenant');});
